### PR TITLE
Develop docs azure

### PR DESCRIPTION
**Pull request by ChrisRisner**
Merging updates with documentation on running training on Microsoft Azure including using a pre-configured VM image, setting up a new custom VM image, and using Azure Container Instances.  This resolves issue #737

### CODE REVIEW

**Comment by xiaomaogy** [comment]
Hi @ChrisRisner, have you tested your azure image with any of the environment that uses visual observation (like grid world)?

**Comment by ChrisRisner** [comment]
Hello @xiaomaogy, I haven't yet tested setting up a virtual screen in order to run testing on environments which do visual observation.  I'll try to carve out some time to try this out and update the docs once I've verified it's working.

**Comment by xiaomaogy** [comment]
@ChrisRisner Also do you mind update the Azure documentation as we've migrated from Tensorflow 1.4 to 1.7.1 please? Also the cuda 8.0 no longer works with Tensorflow 1.4, only CUDA 9.0 works, so that also requires some modification. I will mark your azure documentation as only working with v0.3 for now so that it doesn't confuse people.

**Comment by ChrisRisner** [comment]
@xiaomaogy Thanks for the heads up.  Will work to get this updated as soon as possible.

**Pull request merged**
