### PR TITLE
Updated minor typos (sh for console)

### PR DESCRIPTION
**Pull request by quevedin**
Markdown for Github shows better with that change

### CODE REVIEW

**Comment by unityjeffrey** [comment]
hi @quevedin - thank you for your contribution.  can you change the branch from master to develop?  We don't allow direct contributions to master in this way.  After, we will review / approve.

**Comment by quevedin** [comment]
Sure!

**Comment by quevedin** [comment]
@unityjeffrey , I think I switched the branches correctly, right?

**Comment by unityjeffrey** [comment]
yep @quevedin!

**Comment by unityjeffrey** [comment]
cc: @xiaomaogy

**Comment by xiaomaogy** [comment]
Looks good to me.

**Pull request merged**
