### PR TITLE
added faq to the aws doc

### PR DESCRIPTION
**Pull request by xiaomaogy**
The updated the ami is currently pointing to the release-v0.6 branch. I also added some faq to help people jump through the hurdles I had.

### CODE REVIEW

**Comment by vincentpierre** [comment]
We do have a FAQ document, should the FAQ of this file should go there (Or at least put a link from the FAQ to here?)

**Comment by xiaomaogy** [comment]
@vincentpierre This faq is specific to the aws training, that's why I put them here.

**Comment by xiaomaogy** [comment]
Yes I think adding a link at the FAQ to here make sense.

**Comment by xiaomaogy** [comment]
Hi @vincentpierre, I've resolved all the comments and updated some the faq content.

**Pull request merged**
