### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by midopooler**
### Proposed change(s)

Describe the changes made in this PR.

### Types of change(s)

- [ ] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (please describe)

### Checklist
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Updated the [changelog](https://github.com/Unity-Technologies/ml-agents/blob/master/com.unity.ml-agents/CHANGELOG.md) (if applicable)
- [ ] Updated the [documentation](https://github.com/Unity-Technologies/ml-agents/tree/master/docs) (if applicable)
- [ ] Updated the [migration guide](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Migrating.md) (if applicable)

### CODE REVIEW

**Comment by midopooler** [comment]
Okay, I'll keep this in mind from next time. you may reject this PR.

**Comment by chriselion** [comment]
Were there additional changes to the content, or just the line break changes?

**Comment by midopooler** [comment]
line break changes only.

**Comment by shivaylamba** [comment]
Ok

**Comment by chriselion** [comment]
Ok, in that case, going to close this. Thanks for the contributions on the other PR though.

**Pull request closed without merging**
