### PR TITLE
Removing some scenes

### PR DESCRIPTION
**Pull request by vincentpierre**
### Proposed change(s)

Remove : 
 - All the Static and all the non variable speed environments. 
 - Also removed Bouncer, ~PushBlock~, ~WallJump~ and Reacher. 
 - Removed a bunch of visual environments as well. 
 - Removed ~3DBallHard~ and FoodCollector (kept Visual and Grid FoodCollector)
 - Removed Tennis

This change will break CI, do not merge until CI is ready to be updated
Do not merge before documentation changes are made
Do not merge before configs have been updated

### Useful links (Github issues, JIRA tickets, ML-Agents forum threads etc.)

Done according to this doc : https://docs.google.com/document/d/12rLyHSXaTzbWlXc4-RMjdbVQahzBmOxR-vo4MJ-nxaU/edit#

### Types of change(s)

- [ ] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (please describe)

### Checklist
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Updated the [changelog](https://github.com/Unity-Technologies/ml-agents/blob/master/com.unity.ml-agents/CHANGELOG.md) (if applicable)
- [ ] Updated the [documentation](https://github.com/Unity-Technologies/ml-agents/tree/master/docs) (if applicable)
- [ ] Updated the [migration guide](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Migrating.md) (if applicable)

### CODE REVIEW

**Comment by chriselion** [comment]
Reacher is referenced in the general docs (https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Design-Agents.md#continuous-actions) - not saying we shouldn't remove it, just need to make sure you update that too.

**Comment by awjuliani** [comment]
I don't think we should remove PushBlock or WallJump until we have replacements, such as the PushJump environment.

**Comment by awjuliani** [comment]
https://github.com/Unity-Technologies/ml-agents/blob/develop-remove-some-scenes/docs/images/example-envs.png needs to be modified to remove the old environments.

**Review by awjuliani — COMMENTED** [review]
Only issue I found on a quick look through all the docs was the presence of a now-outdated image of all the environments together.

**Comment by vincentpierre** [comment]
> https://github.com/Unity-Technologies/ml-agents/blob/develop-remove-some-scenes/docs/images/example-envs.png needs to be modified to remove the old environments.

Yes, I was wondering about that image. On one hand, I think it looks good for posterity (a little bit of nostalgia), on the other, these are outdated... I can try to make a new one and ask for feedback on slack.

**Comment by vincentpierre** [comment]
Here is a proposal for the new examples image : https://github.com/Unity-Technologies/ml-agents/pull/4997/commits/f46559efbb29c6992b69bece128471557e4f621f?short_path=a30098f#diff-a30098fd97aa8ab52ef89a72529f76207e044fcc33856d2e908dedd20e6a825a

**Comment by awjuliani** [comment]
New image looks good to me.

**Review by awjuliani — APPROVED** [review]

**Comment by vincentpierre** [comment]
@awjuliani Here is the PR to modify the CI tests accordingly. Please review : https://github.com/Unity-Technologies/ml-agents-cloud-internal/pull/292

**Pull request merged**
