### PR TITLE
WIP: Enable finetuning from previous models 

### PR DESCRIPTION
**Pull request by ervteng**
@awjuliani remembered that finetuning was actually a pretty heavily requested feature from users, so might as well put it in :P 

@awjuliani @vincentpierre Wanted to get your thoughts on UI for something like this. In this PR, it requires the user to put into the trainer_config the _full path_ to the model (e.g. `models/run_id-0/BrainName`) and run with `--load`. We could also:

- Automatically load even without `--load`, if a `finetune_path` is provided. 
- Require that the brain names match

### CODE REVIEW

**Comment by vincentpierre** [comment]
I think we should actually replace the load feature entirely. It seems it is just a worst version of what you are proposing.

**Comment by ervteng** [comment]
@vincentpierre if we replace the load feature, how do we resume from an existing checkpoint? (not finetune)? 

I would almost support loading by default, and requiring a different `run-id` to retrain. The number of times I've accidentally overwrote the old model is quite high

**Comment by ervteng** [comment]
@awjuliani I tested this on Snoopy Pop (finetune from a levels 1-10 bot to level 25) and it was considerably worse than training from scratch. 

Won't be merging this PR as-is, but you're right, we should have a deeper discussion about giving such a feature to our users. Could also tie into generalization of agents across games.

**Comment by chriselion** [comment]
Changing target from develop to master.

**Comment by ervteng** [comment]
This feature has been implemented as `--initialize-from`. Closing this PR.

**Pull request closed without merging**
