### PR TITLE
Use dotnet 8.x in pre-commits to fix flaky failures

### LINKED ISSUE #80619: IOException running NuGet-Migrations during tests in dotnet CLI first run
This is affecting 6.0, 7.0 and 8.0.

In https://github.com/dotnet/runtime/pull/80510#issuecomment-1382160934 we saw a failure because some NuGet migration code failed to run during the dotnet CLI first run experience:

```
+ dotnet /datadisks/disk1/work/ADFC09B1/p/xunit/xunit.console.dll JIT/HardwareIntrinsics/JIT.HardwareIntrinsics.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml -trait TestGroup=JIT.HardwareIntrinsics.Arm.ArmBase
Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET 7.0.2)
  Discovering: JIT.HardwareIntrinsics.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  JIT.HardwareIntrinsics.XUnitWrapper (found 6 of 362 test cases)
  Starting:    JIT.HardwareIntrinsics.XUnitWrapper (parallel test collections = on, max threads = 2)
    JIT/HardwareIntrinsics/Arm/ArmBase.Arm64/ArmBase.Arm64_ro/ArmBase.Arm64_ro.sh [FAIL]
      System.IO.IOException: The system cannot open the device or file specified. : 'NuGet-Migrations'
         at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
         at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
         at NuGet.Common.Migrations.MigrationRunner.Run()
         at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
         at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider, Dictionary`2 performanceMeasurements)
         at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
         at Microsoft.DotNet.Cli.Program.Main(String[] args)
      
      Return code:      1
```

We should look into disabling the first run experience via the `DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1` env var, it doesn't make sense to run that for the tests.

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[368683](https://dev.azure.com/dnceng-public/public/_build/results?buildId=368683)|dotnet/runtime|[JIT.Methodical.eE.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=368683&view=ms.vss-test-web.build-test-results-tab&runId=7815400&resultId=102496)|dotnet/runtime#90241|
|[362596](https://dev.azure.com/dnceng-public/public/_build/results?buildId=362596)|dotnet/runtime|[JIT.Methodical.eE.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=362596&view=ms.vss-test-web.build-test-results-tab&runId=7661116&resultId=102496)|dotnet/runtime#89003|
|[361655](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361655)|dotnet/runtime|[JIT.Math.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361655&view=ms.vss-test-web.build-test-results-tab&runId=7638022&resultId=102855)|dotnet/runtime#89905|
|[361259](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361259)|dotnet/runtime|[JIT.Generics.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361259&view=ms.vss-test-web.build-test-results-tab&runId=7627032&resultId=102496)||
|[361075](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361075)|dotnet/runtime|[JIT.Regression.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361075&view=ms.vss-test-web.build-test-results-tab&runId=7622388&resultId=102856)|dotnet/runtime#89867|
|[360768](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360768)|dotnet/runtime|[JIT.Regression.JitBlue.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360768&view=ms.vss-test-web.build-test-results-tab&runId=7614654&resultId=102855)|dotnet/runtime#89815|
|[360148](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360148)|dotnet/runtime|[JIT.jit64.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360148&view=ms.vss-test-web.build-test-results-tab&runId=7598234&resultId=102496)|dotnet/runtime#89814|
|[359522](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359522)|dotnet/runtime|[JIT.Methodical.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359522&view=ms.vss-test-web.build-test-results-tab&runId=7580578&resultId=102496)|dotnet/runtime#89805|
|[356421](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356421)|dotnet/runtime|[JIT.Methodical.a-dA-D.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356421&view=ms.vss-test-web.build-test-results-tab&runId=7498350&resultId=102496)||
|[355235](https://dev.azure.com/dnceng-public/public/_build/results?buildId=355235)|dotnet/runtime|[JIT.Methodical.f-iF-I.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=355235&view=ms.vss-test-web.build-test-results-tab&runId=7471180&resultId=102496)|dotnet/runtime#89009|
|[343534](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343534)|dotnet/runtime|[JIT.Methodical.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343534&view=ms.vss-test-web.build-test-results-tab&runId=7177384&resultId=102496)||
|[342037](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342037)|dotnet/runtime|[JIT.Regression.JitBlue.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342037&view=ms.vss-test-web.build-test-results-tab&runId=7142106&resultId=102855)|dotnet/runtime#89008|
|[341937](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341937)|dotnet/runtime|[JIT.Methodical.a-dA-D.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341937&view=ms.vss-test-web.build-test-results-tab&runId=7140062&resultId=102496)|dotnet/runtime#89003|
|[337982](https://dev.azure.com/dnceng-public/public/_build/results?buildId=337982)|dotnet/runtime|[JIT.HardwareIntrinsics.X86.Avx2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=337982&view=ms.vss-test-web.build-test-results-tab&runId=7032408&resultId=102855)|dotnet/runtime#88809|
|[337742](https://dev.azure.com/dnceng-public/public/_build/results?buildId=337742)|dotnet/runtime|[JIT.Regression.CLR-x86-JIT.V1-M12-M13.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=337742&view=ms.vss-test-web.build-test-results-tab&runId=7025630&resultId=102496)|dotnet/runtime#88769|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|15|

### Known Issue Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorPattern": "The system cannot open the device or file specified. : (&#39;|')NuGet-Migrations(&#39;|')",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** 
**Result validation: :warning:** Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build: :mag_right:**" line.
**Validation performed at:** 6/28/2023 10:04:55 PM UTC

### PR DESCRIPTION
**Pull request by alex-mccarthy-unity**
### Proposed change(s)

The 8.x release should contain https://github.com/dotnet/runtime/pull/90342 which fixes https://github.com/dotnet/runtime/issues/80619.

I hope this will fix flaky failures like https://github.com/Unity-Technologies/ml-agents/actions/runs/8268945605/job/22623023348 of the form:
```
dotnet-format............................................................Failed
- hook id: dotnet-format
- exit code: 1

System.IO.IOException: The system cannot open the device or file specified. : 'NuGet-Migrations'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at NuGet.Common.Migrations.MigrationRunner.Run(String migrationsDirectory)
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider, Dictionary`2 performanceMeasurements)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

### Types of change(s)

- [x] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (please describe)

### Checklist
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Updated the changelog (if applicable)
- [ ] Updated the documentation (if applicable)
- [ ] Updated the migration guide (if applicable)

### CODE REVIEW

**Review by miguelalonsojr — APPROVED** [review]
Let it fly!

**Comment by alex-mccarthy-unity** [comment]
Unfortunately, we still see the same failure after this change :( https://github.com/Unity-Technologies/ml-agents/actions/runs/8278579680/job/22651228262

**Comment by Namanl2001** [comment]
@alex-mccarthy-unity I'm facing the same issue with v8.0.2

did you find or know of any workaround for this? thanks!

**Comment by alex-mccarthy-unity** [comment]
> @alex-mccarthy-unity I'm facing the same issue with v8.0.2
> 
> did you find or know of any workaround for this? thanks!

Unfortunately I don't know of any solutions :( I've found that retrying failed tasks has a good chance of the retry succeeding, but I know that that's an unsatisfying workaround.

**Pull request merged**
