### PR TITLE
New model for the dynamic crawler

### PR DESCRIPTION
**Pull request by vincentpierre**

### CODE REVIEW

**Comment by xiaomaogy** [comment]
I cannot drag the model bytes file inside the CrawlerDynamicLearning asset. Maybe I am still not clear how it works...

**Comment by vincentpierre** [comment]
There is no more `.bytes` file, there is only `.tf` files now. Are you sure you have the right branch ?

**Comment by xiaomaogy** [comment]
Sorry, yes I meant .tf file. I checked out the release-v0.6-dynamic-crawler-model branch and put in the dll files and tried, and the LearningBrain asset doesn't take it.

**Comment by awjuliani** [comment]
Works great!

**Pull request merged**
