### PR TITLE
Fix analytics error when compiling XBOX and PS5

### PR DESCRIPTION
**Pull request by hvpeteet**
### Proposed change(s)

Bugfix: Turns off analytics for platforms that don't support them. To use analytics safely you must wrap usage with `#if ENABLE_CLOUD_SERVICES_ANALYTICS
` 
See https://docs.unity3d.com/ScriptReference/Analytics.Analytics.html

### Useful links (Github issues, JIRA tickets, ML-Agents forum threads etc.)

Internal JIRA: https://jira.unity3d.com/browse/MLA-2151

### Types of change(s)

- [x] Bug fix

### Testing

Errors went away when compiling for XBox in windows VM

ALSO: 2020.3 is failing because of an existing issue https://jira.unity3d.com/browse/MLA-2311

### CODE REVIEW

**Review by maryamhonari — APPROVED** [review]
LGTM. Would you add a line to the change log? thanks!

**Comment by hvpeteet** [comment]
> LGTM. Would you add a line to the change log? thanks!

Done, thanks for the catch.

**Review by jrupert-unity — APPROVED** [review]
LGTM in terms of addressing the issue.  I'm wondering if we need all three of UNITY_EDITOR , MLA_UNITY_ANALYTICS_MODULE and ENABLE_CLOUD_SERVICES_ANALYTICS in these checks  and if they could be made more consistent.  This is something that could be looked at separately if there's a question about it.

**Comment by hvpeteet** [comment]
> I'm wondering if we need all three of UNITY_EDITOR , MLA_UNITY_ANALYTICS_MODULE and ENABLE_CLOUD_SERVICES_ANALYTICS in these checks and if they could be made more consistent. 

👍   was mainly just trying to get a fix in before the release. I feel like this could be pruned down and we could commit to just using [conditional attributes ](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.conditionalattribute) (already used in this code alongside the preprocessor directives), but I wasn't sure of all the edge cases with analytics so I played it safe and just added onto the existing directives.

**Pull request merged**
