### PR TITLE
Clarify documentation for step() in Python-API.md - Only API Docs

### PR DESCRIPTION
**Pull request by akmadian**
- Indent the section about providing actions to multiple brains to be in line with the rest of the step() docs.
 - Move the line about what step() returns closer to the top of the docs so it's harder to overlook.
 - Add a small code snippet about how to get BrainInfo belonging to a specific brain and how to get data from that BrainInfo object.

### CODE REVIEW

**Comment by akmadian** [comment]
Here's the new pr :) @awjuliani

**Comment by awjuliani** [comment]
Looks good! Merging in :-)

**Comment by akmadian** [comment]
I accidentally reversed the explicit documentation of the Jupyter notebook location. Should I create a new pr to fix it?

**Comment by awjuliani** [comment]
Just noticed that. Please feel free to.

**Pull request merged**
