### PR TITLE
documentation touchups

### PR DESCRIPTION
**Pull request by codethulu**
#### Getting-Started.md
* There was an inconsistency in the `--run-id` provided in the example

#### Learning-Environment-Create-New
* Renames `speed` to `forceMultiplier`, since that's what it is.
* Adds a link to Learning-Environment-Design-Agents.md for reference when asking the user to change a value
* Adds a link to Training-Configuration-File.md for reference near the hyperparameters.

### Useful links (Github issues, JIRA tickets, ML-Agents forum threads etc.)
n/a

### Types of change(s)

- [ ] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Breaking change
- [x] Documentation update
- [ ] Other (please describe)

### Checklist
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Updated the [changelog](https://github.com/Unity-Technologies/ml-agents/blob/master/com.unity.ml-agents/CHANGELOG.md) (if applicable)
- [ ] Updated the [documentation](https://github.com/Unity-Technologies/ml-agents/tree/master/docs) (if applicable)
- [ ] Updated the [migration guide](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Migrating.md) (if applicable)

### CODE REVIEW

**Comment by andrewcoh** [comment]
Hi @codethulu 

Can you please sign our CLA so that we can consider merging this?

Thanks.

**Comment by codethulu** [comment]
> Hi @codethulu
> 
> Can you please sign our CLA so that we can consider merging this?
> 
> Thanks.

uhhh... sure? thought it would be covered by the whole employment thing though :S

**Comment by codethulu** [comment]
> Hi @codethulu
> 
> Can you please sign our CLA so that we can consider merging this?
> 
> Thanks.

@andrewcoh also it looks like i signed this on the 6th? not sure how to sign it again or why SAP hasn't processed it since it displays as signed when i click through..

**Comment by chriselion** [comment]
Maybe try the "Let us recheck it." link in the message from the bot?

**Comment by codethulu** [comment]
> Maybe try the "Let us recheck it." link in the message from the bot?

i clicked that twice just now, but have no idea what tasks it does or doesn't spawn 🤷

**Pull request merged**
