### PR TITLE
Feature/google collab example

### PR DESCRIPTION
**Pull request by ugurkanates**
### Proposed change(s)

Given  issue #3984 and removal of Jupyter Notebooks from repository , I saw developers were chatting for a Colab API explanatory notebook. 
Well I have set up just that. Which shows how to use low level Python API and randomly moves in environments. It works both for continuous and discrete environments 

I have a question about where to store / if to store headless binaries that are needed for this.
In current version I have uploaded whole binary+ data files to my repository. I didn't include them in here due size but given solution technique I can upload them.

These binaries build with latest version of each package ( C#Unity com Package ,  release 1.0 Python packages)

### Useful links (Github issues, JIRA tickets, ML-Agents forum threads etc.)

https://forum.unity.com/threads/ml-agents-release-1-april-30-2020-discussion-thread.882919/
https://github.com/Unity-Technologies/ml-agents/issues/3984

### Types of change(s)

- [ ] Bug fix
- [X] New feature
- [ ] Code refactor
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (please describe)

### Checklist
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Updated the [changelog](https://github.com/Unity-Technologies/ml-agents/blob/master/com.unity.ml-agents/CHANGELOG.md) (if applicable)
- [ ] Updated the [documentation](https://github.com/Unity-Technologies/ml-agents/tree/master/docs) (if applicable)
- [ ] Updated the [migration guide](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Migrating.md) (if applicable)

### Other comments
After a code review & how to store binaries  I can update notebook and README.md

### CODE REVIEW

**Comment by awjuliani** [comment]
Hi @ugurkanates 

Thanks for making this PR. We actually have another open PR which will hopefully provide just the functionality needed to easily download binaries from the python api itself. It is still being worked on, but it should perfectly complement the work you have here: https://github.com/Unity-Technologies/ml-agents/pull/3967

**Comment by ugurkanates** [comment]
@awjuliani  Yeah that should fix storage problem relating to binaries. I will keep eye on that PR

**Comment by ugurkanates** [comment]
@awjuliani 

So I was updating notebook to work with current registry system(that's available in master branch). 
But couldn't find a file provider to hold files with their original file prefixes. I was trying Google Drive but that doesn't provide a file prefix. Only their convoluted codenames for upload.

Also for example I uploaded one for continuous actions and one for discrete actions but yeah. 
Hope you guys can help with hosting these files in Google Cloud services you have.

Another thing was depending on situation I will have one Notebook file and one yaml. If Colab examples added to default registry I wouldn't need yaml. Current default registry ones are all built with visual servers which doesn't work with headless Google Colab services.

Headless versions work fine(I provided zips below).  So if uploading them to Google Cloud Buckets and adding them to yaml is possible that would be nice. 

Where should Colab notebook be hold in repository by the way? couldn't find a proper place for it honestly. I was even thinking dropping into main repository files along with readme
Utils and Docs also could be a possibility but yeah.


[](environments:
  - BasicColab:
     expected_reward: 0.93
     description: https://github.com/Unity-Technologies/ml-agents/blob/release_1/docs/Learning-Environment-Examples.md#basic
     linux_url: https://drive.google.com/u/0/uc?export=download&confirm=scux&id=19xQab1vJet4zZKWewpyDyEyiflcodx1d
     darwin_url: ""
     win_url: ""
   
  - CrawlerStaticTargetColab:
     expected_reward: 2000
     description: https://github.com/Unity-Technologies/ml-agents/blob/release_1/docs/Learning-Environment-Examples.md
     linux_url: https://drive.google.com/u/0/uc?export=download&confirm=P2Bu&id=14HcSMDmofd-SP2Q1BANViePFZGrkhneB
     darwin_url: ""
     win_url: "")

**Comment by awjuliani** [comment]
Hi @ugurkanates 

I am assigning @vincentpierre to this issue, as he has been working on the registry solution, and doing some experimentation with colab notebooks.

**Comment by vincentpierre** [comment]
I merged #4117 which adds links to 3 google colab notebooks to serve as tutorial. Closing this now.

**Pull request closed without merging**
