### PR TITLE
Replaced the Unity logo with a better one

### PR DESCRIPTION
**Pull request by vincentpierre**
I took an image online, but we can use anything.

### CODE REVIEW

**Comment by mmattar** [comment]
@vincentpierre - can you attach the image to the PR Description?

Also, where did you get in online?

**Comment by vincentpierre** [comment]
Unity-1200X630_crop
I found the image [here](https://unity3d.com/public-relations/downloads) and I cropped it 

Looks like this in my terminal
Screen Shot 2020-05-13 at 2 22 06 PM

**Comment by awjuliani** [comment]
@vincentpierre What about people with white background terminals?

**Comment by vincentpierre** [comment]
> @vincentpierre What about people with white background terminals?

We link to a tutorial on how to use better background color for their terminals.

Screen Shot 2020-05-13 at 2 42 00 PM

**Comment by ervteng** [comment]
Hate to ask this, but does it work on Windows CMD?

**Comment by surfnerd** [comment]
> Hate to ask this, but does it work on Windows CMD?

I was going to ask if it works on all terminals

**Comment by ervteng** [comment]
image
Windows

**Comment by vincentpierre** [comment]
Welp

**Pull request closed without merging**
