### PR TITLE
Limit pytest <4.0.0

### PR DESCRIPTION
**Pull request by harperj**
Some of our tests fail with the new pytest v4.0.x versions because of
a change to how fixtures work. Since these versions are the latest
release in PyPI now, unit tests will fail on a fresh install.

This change limits the version range in setup.py to fix the issue
until we can make a decision about upgrading.

### CODE REVIEW

**Comment by vincentpierre** [comment]
Since you are changing that file, could you also merge requirements.txt into setup.py ?

**Comment by harperj** [comment]
@vincentpierre it looks like requirements.txt is already a subset of the information of setup.py.  Do you mean to say we should remove requirements.txt?

**Comment by vincentpierre** [comment]
Yes, I do not think requirements.txt is used anywhere anymore

**Comment by harperj** [comment]
There was one additional reference in `Installation.md`.  I believe this would also need to be fixed in the localized version but I've fixed it in the English version.

**Pull request merged**
