### PR TITLE
Cold fix to develop : documentation for Engine Configuration

### PR DESCRIPTION
**Pull request by vincentpierre**

### CODE REVIEW

**Comment by ervteng** [comment]
Should we add the new command line options to the getting started guide? (The line where they run `mlagents-learn --train`, we'll also need to pass a timescale arg right?).

**Comment by chriselion** [comment]
I believe we'll default to the old behavior (timescale = 100) right?

**Comment by vincentpierre** [comment]
default is 20 right now. I think 100 breaks some of our environments.

**Comment by ervteng** [comment]
> default is 20 right now. I think 100 breaks some of our environments.

Hunter tweaked some of the timescales in the env update. 100 causes tunnelling in e.g. Hallway, the cube will go through the wall.

**Comment by chriselion** [comment]
Ah, I was just looking at the default in the old code.

**Pull request merged**
