### PR TITLE
Changing location of template file

### PR DESCRIPTION
**Pull request by anupambhatnagar**
The PR template file needs to be in the .github folder and cannot be in a sub-folder. It does not render if it is in a sub-folder.

### CODE REVIEW

**Comment by chriselion** [comment]
Not sure this is right either (upper case file name).

[This](https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository) makes it sound like either of these would work
* `.github/pull_request_template.md`
* `.github/PULL_REQUEST_TEMPLATE/pull_request_template.md`

**Comment by anupambhatnagar** [comment]
The last paragraph on this [page](https://help.github.com/en/enterprise/2.19/user/github/building-a-strong-community/about-issue-and-pull-request-templates#pull-request-templates) mentions that the name is not case sensitive but it needs to be in the `.github` folder.

**Comment by anupambhatnagar** [comment]
you are correct @chriselion. I'll change the folder name to PULL_REQUEST_TEMPLATE

**Comment by anupambhatnagar** [comment]
@chriselion the PR is not generated even after this change. Based on [this](https://github.com/ionic-team/ionic/blob/master/.github/PULL_REQUEST_TEMPLATE.md) example I'm changing the filename to uppercase and putting it in the `.github` folder.

**Pull request merged**
