### PR TITLE
enable markdown prettier, apply to one file

### PR DESCRIPTION
**Pull request by chriselion**
### Proposed change(s)

Describe the changes made in this PR.

### Types of change(s)

- [ ] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (please describe)

### Checklist
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Updated the [changelog](https://github.com/Unity-Technologies/ml-agents/blob/master/com.unity.ml-agents/CHANGELOG.md) (if applicable)
- [ ] Updated the [documentation](https://github.com/Unity-Technologies/ml-agents/tree/master/docs) (if applicable)
- [ ] Updated the [migration guide](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Migrating.md) (if applicable)

### CODE REVIEW

**Comment by chriselion** [comment]
@mmattar Let me know if you like this and want me to roll it out more widely (I can also wait until your current PRs are landed, or pick some different guinea pigs).

**Comment by mmattar** [comment]
This looks great. As I'm touching most of the pages with my PRs, I can roll this out with each PR (on the specific pages). Then we can roll it out to the entire repo.

**Comment by chriselion** [comment]
So do you want me to merge this as is, or pick a different file to whitelist? Or nothing to start with?

**Comment by mmattar** [comment]
I'd say nothing to start.

I just pushed the first "prettier" PR #3782 as a follow-up to PR #3775

**Pull request closed without merging**
