### PR TITLE
Update Training-on-Amazon-Web-Service.md

### PR DESCRIPTION
**Pull request by Balintskac**
It is a typo instead of 87 , it is 67.

### Proposed change(s)

Describe the changes made in this PR.

### Types of change(s)

- [x] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (please describe)

### Checklist
- [x] Added tests that prove my fix is effective or that my feature works
- [ ] Updated the [changelog](https://github.com/Unity-Technologies/ml-agents/blob/master/com.unity.ml-agents/CHANGELOG.md) (if applicable)
- [ ] Updated the [documentation](https://github.com/Unity-Technologies/ml-agents/tree/master/docs) (if applicable)
- [ ] Updated the [migration guide](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Migrating.md) (if applicable)

### CODE REVIEW

**Comment by Balintskac** [comment]
Typo correction

**Review by chriselion — APPROVED** [review]
Looks good, thanks

**Comment by chriselion** [comment]
You need to accept the Contributor License Agreement before I can merge this.

**Comment by Balintskac** [comment]
Fixed typo

**Pull request merged**
