### PR TITLE
Make Gym interface work with grayscale and RGB visual observations

### PR DESCRIPTION
**Pull request by shakenes**
Hi everybody,
I recently ran into issues when processing multiple visual observations that contain both, RGB and grayscale images, with the OpenAI Gym interface.

I edited the ` _single_step` function accordingly and now it should work.

What do you think?

Sorry for the second PR. Apparently, something went wrong with my git settings...

### CODE REVIEW

**Comment by unityjeffrey** [comment]
hi @shakenes - can you change the branch to Develop from Master?

**Comment by unityjeffrey** [comment]
hi @shakenes - just a friendly reminder to change your target branch to Develop.  We do not accept direct contributions to Master in this way.

**Comment by shakenes** [comment]
Sorry for the delay. Just changed it!

**Comment by unityjeffrey** [comment]
thank you for your contribution @shakenes!

**Pull request merged**
