### PR TITLE
KR README Translate

### PR DESCRIPTION
**Pull request by xogur6889**
### Proposed change(s)

Describe the changes made in this PR.

### Types of change(s)

- [ ] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Breaking change
- [x] Documentation update
- [ ] Other (please describe)

### Checklist
- [x] Added tests that prove my fix is effective or that my feature works
- [ ] Updated the [changelog](https://github.com/Unity-Technologies/ml-agents/blob/master/com.unity.ml-agents/CHANGELOG.md) (if applicable)
- [ ] Updated the [documentation](https://github.com/Unity-Technologies/ml-agents/tree/master/docs) (if applicable)
- [ ] Updated the [migration guide](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Migrating.md) (if applicable)

### CODE REVIEW

**Review by xogur6889 — COMMENTED** [review]
I worked on translation from English to Korean.

**Comment by xogur6889** [comment]
@Chris Elion

**Review by xogur6889 — COMMENTED** [review]
Review

**Comment by unityjeffrey** [comment]
@xogur6889 - we will ask local translator for some help.

**Comment by xogur6889** [comment]
> @xogur6889 - we will ask local translator for some help.

I already told the person who worked on the translation(This is the "local translator" you're talking about, right?). But if you ask him again, I'll wait.

**Comment by unityjeffrey** [comment]
hi @xogur6889 - someone from the team did a review and made some suggested changes.  I've attached his review in this comment.  Can you make the edits and I will approve?

[README.md.zip](https://github.com/Unity-Technologies/ml-agents/files/5967098/README.md.zip)

Thank you for your contribution!

**Comment by xogur6889** [comment]
hi @unityjeffrey
I listened to your opinion and edited it as a new README file. Is everything all right?

**Comment by jmercado1985** [comment]
hi @xogur6889 - I just had someone from the team confirm that everything is alright.

**Review by jmercado1985 — APPROVED** [review]
Approved. Confirmed changes with internal team member.

**Pull request merged**
