### PR TITLE
enable 3D Ball sample import button in package manager for unity sdk

### PR DESCRIPTION
**Pull request by xcao65**
### Proposed change(s)

Enable import sample functionality for ml-agents unity package so that Unity Editor users can directly import samples into their project instead of copy from ml-agents repo.
Asked by an instructor in this video: https://youtu.be/_9aPZH6pyA8?t=49

This feature has been developed by Chris Goy: https://github.com/Unity-Technologies/ml-agents/pull/5077
But it is missing some parts to work.

### Useful links (Github issues, JIRA tickets, ML-Agents forum threads etc.)
Import Samples Doc: https://docs.unity3d.com/2021.2/Documentation/Manual/cus-samples.html

### Types of change(s)
- [x] New feature

### Checklist
N/A

### Other comments
Verified locally with Unity Editor by adding package from disk in package manager

### CODE REVIEW

**Review by hvpeteet — COMMENTED** [review]
Were you able to confirm this working locally with the change?

**Comment by xcao65** [comment]
> Were you able to confirm this working locally with the change?

Yes. I was able to run 
`/Applications/Unity/Hub/Editor/2018.4.32f1/Unity.app/Contents/MacOS/Unity -projectPath ~/code/ml-agents-01/Project -batchMode -executeMethod Unity.MLAgents.SampleExporter.ExportCuratedSamples -logFile -`

and import package locally using Unity Editor.

But I have a question regarding the `pack` job

**Comment by xcao65** [comment]
> > Were you able to confirm this working locally with the change?
> 
> Yes. I was able to run `/Applications/Unity/Hub/Editor/2018.4.32f1/Unity.app/Contents/MacOS/Unity -projectPath ~/code/ml-agents-01/Project -batchMode -executeMethod Unity.MLAgents.SampleExporter.ExportCuratedSamples -logFile -`
> 
> and import package locally using Unity Editor.
> 
> But I have a question regarding the `pack` job

How can i confirm this job completes before ml-agents Unity SDK release?
https://github.com/Unity-Technologies/ml-agents/blob/main/.yamato/com.unity.ml-agents-pack.yml

**Comment by hvpeteet** [comment]
> > > Were you able to confirm this working locally with the change?
> > 
> > 
> > Yes. I was able to run `/Applications/Unity/Hub/Editor/2018.4.32f1/Unity.app/Contents/MacOS/Unity -projectPath ~/code/ml-agents-01/Project -batchMode -executeMethod Unity.MLAgents.SampleExporter.ExportCuratedSamples -logFile -`
> > and import package locally using Unity Editor.
> > But I have a question regarding the `pack` job
> 
> How can i confirm this job completes before ml-agents Unity SDK release? https://github.com/Unity-Technologies/ml-agents/blob/main/.yamato/com.unity.ml-agents-pack.yml

I think you should be able to see the job in the checks section on Github. E.g. https://unity-ci.cds.internal.unity3d.com/job/10775272.

**Review by hvpeteet — APPROVED** [review]
LGTM, thanks Xun

**Review by jrupert-unity — COMMENTED** [review]
lgtm - testing is probably more important than review since I'm not sure I'd catch a problem.

**Pull request merged**
