### PR TITLE
Reverting bug introduced in #4071

### PR DESCRIPTION
**Pull request by vincentpierre**
### Proposed change(s)

Describe the changes made in this PR.

### Types of change(s)

- [x] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (please describe)

### Checklist
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Updated the [changelog](https://github.com/Unity-Technologies/ml-agents/blob/master/com.unity.ml-agents/CHANGELOG.md) (if applicable)
- [ ] Updated the [documentation](https://github.com/Unity-Technologies/ml-agents/tree/master/docs) (if applicable)
- [ ] Updated the [migration guide](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Migrating.md) (if applicable)

### CODE REVIEW

**Comment by ervteng** [comment]
Why did the original PR break just FoodCollector?

**Comment by vincentpierre** [comment]
> Why did the original PR break just FoodCollector?

Because of all our example environments, only FoodCollector has a dependency on EnvironmentReset

**Comment by ervteng** [comment]
> > Why did the original PR break just FoodCollector?
> 
> Because of all our example environments, only FoodCollector has a dependency on EnvironmentReset

Should we add a unit test for EnvironmentReset?

**Comment by vincentpierre** [comment]
> Should we add a unit test for EnvironmentReset?

We do not have a way to unit test when the Python communication is happening. This bug does not happen at inference

**Comment by ervteng** [comment]
> > Should we add a unit test for EnvironmentReset?
> 
> We do not have a way to unit test when the Python communication is happening. This bug does not happen at inference

Sounds good. I guess this sounds like a Yamato test but it's probably out-of-scope for this PR.

**Pull request merged**
