### PR TITLE
TensorFlowSharp is no more

### PR DESCRIPTION
**Pull request by vincentpierre**

### CODE REVIEW

**Comment by chriselion** [comment]
You can get rid of https://github.com/Unity-Technologies/ml-agents/blob/develop/docs/Using-TensorFlow-Sharp-in-Unity.md too

**Comment by chriselion** [comment]
And this section too
https://github.com/Unity-Technologies/ml-agents/blob/develop/docs/FAQ.md#tensorflowsharp-flag-not-turned-on

**Comment by vincentpierre** [comment]
I left them on purpose since those docs are more migration things. Is the FAQ linked only to the current version ?

**Comment by chriselion** [comment]
Yeah, I don't think we should refer to removed features in the current FAQ

**Comment by awjuliani** [comment]
RIP TF#.

**Comment by FromZeus** [comment]
@vincentpierre @chriselion Guys, I'm just getting into this stuff but can I ask you why are you getting rid off of TF#? I just wanted to research TF# and use it in Unity.

**Comment by vincentpierre** [comment]
@FromZeus We are now using the Unity Inference Engine to do inference within Unity Games. For this reason, we deprecated our support for TF#.

**Comment by FromZeus** [comment]
@vincentpierre Got it, thank you for the information!

**Pull request merged**
