### PR TITLE
Fixing tensorboard command line params

### PR DESCRIPTION
**Pull request by niskander**
### Proposed change(s)
"--logdir=results" is broken in newer versions of tensorboard; "logdir results" without the equal sign works. 

### Useful links (Github issues, JIRA tickets, ML-Agents forum threads etc.)
See https://github.com/tensorflow/tensorboard/issues/686 
This is also how they do it in updated docs https://www.tensorflow.org/tensorboard/scalars_and_keras

### Types of change(s)

- [x] Bug fix

### CODE REVIEW

**Comment by chriselion** [comment]
Hi @niskander, thanks for catching this!

It looks like there are few other places where we have a tensorboard commandline with `=` in it:
```shell
$ git grep -i tensorboard.*logdir
docs/Getting-Started.md:tensorboard --logdir=results
docs/Training-on-Microsoft-Azure.md:   `tensorboard --logdir=summaries --host 0.0.0.0`
docs/Using-Docker.md:docker exec -it <container-name> tensorboard --logdir=/unity-volume/summaries --host=0.0.0.0
docs/Using-Docker.md:docker exec -it 3DBallContainer.first.trial tensorboard --logdir=/unity-volume/summaries --host=0.0.0.0
docs/Using-Tensorboard.md:1. From the command line run: `tensorboard --logdir=results --port=6006`
```
(and some are still using the old `summaries` directory too). Would you mind updating those too? Or I can make the changes on your branch if you'd prefer.

**Comment by niskander** [comment]
@chriselion I made the change in the other files as well! 

@CLAassistant is asking me to resign the CLA (which I cannot do since it's already signed...)

Screen Shot 2020-07-24 at 2 36 54 AM

**Comment by chriselion** [comment]
Weird, it says `664allthethings` pushed the changes. Is that a personal account?

**Comment by niskander** [comment]
@chriselion yes apparently? That was really weird... I signed it with the other account as well.

**Comment by chriselion** [comment]
Looks good, thanks again for fixing this!

**Pull request merged**
