### PR TITLE
added BehaviorParameters icon to package

### PR DESCRIPTION
**Pull request by Hunter-Unity**
### Proposed change(s)

Adds an icon to the BehaviorParameters script.

### Types of change(s)

- [ ] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (please describe)

### Checklist
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Updated the [changelog](https://github.com/Unity-Technologies/ml-agents/blob/master/com.unity.ml-agents/CHANGELOG.md) (if applicable)
- [ ] Updated the [documentation](https://github.com/Unity-Technologies/ml-agents/tree/master/docs) (if applicable)
- [ ] Updated the [migration guide](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Migrating.md) (if applicable)

### CODE REVIEW

**Comment by chriselion** [comment]
Is there a guideline for the suggested resolution? It looks a lot larger than the ones in https://github.cds.internal.unity3d.com/unity/unity-editor-icons/tree/master/Dark/Machine%20Learning

**Comment by Hunter-Unity** [comment]
I'll check with the UX team for sizing

**Comment by chriselion** [comment]
Sounds good.

**Comment by miguelalonsojr** [comment]
Closing this PR as stale.

**Pull request closed without merging**
