### PR TITLE
Fix gpu pytests

### PR DESCRIPTION
**Pull request by dongruoping**
### Proposed change(s)

Move tensors to cpu before converting it to numpy

### Types of change(s)

- [x] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (please describe)

### Checklist
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Updated the [changelog](https://github.com/Unity-Technologies/ml-agents/blob/main/com.unity.ml-agents/CHANGELOG.md) (if applicable)
- [ ] Updated the [documentation](https://github.com/Unity-Technologies/ml-agents/tree/main/docs) (if applicable)
- [ ] Updated the [migration guide](https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Migrating.md) (if applicable)

### CODE REVIEW

**Review by andrewcoh — APPROVED** [review]

**Comment by chriselion** [comment]
Does this affect release 13? If so, we should probably do a hotfix release...

**Comment by chriselion** [comment]
Also, would it explain https://forum.unity.com/threads/im-getting-runtimeerror-rnn-hx-is-not-contiguos.1066898/ ?

**Comment by dongruoping** [comment]
@chriselion  This is affected by #4939 and I think the release is safe.
The forum post seems to be a different issue and that should have already been resolved in the latest version.

**Comment by chriselion** [comment]
👍 Thanks for clarifying.

**Pull request merged**
