### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by GeriBP**
In an empty project I get a compilation error after importing the ML-Agents folder that contains all scripts and examples.

This is the error log:

Assets/ML-Agents/Scripts/ExternalCommunicator.cs(269,24): error CS1061: Type `System.Text.StringBuilder' does not contain a definition for `Clear' and no extension method `Clear' of type `System.Text.StringBuilder' could be found. Are you missing an assembly reference?

### CODE REVIEW

**Comment by vincentpierre** [comment]
@GeriBP Are you getting this on master, develop or both? Did you make sure you were targeting .NET 4.6 in Api Compatibility Level under player settings ?

**Comment by GeriBP** [comment]
I was getting it on master. I was freaking out a bit with all the new changes and this error and didn't change my player settings for ml agents... Sorry for the inconvenience, problem solved.
And thanks for the lighting fast reply. You guys seriously rock!!!!

**Comment by GeriBP** [comment]
Hi again @vincentpierre , sorry to be annoying but I'm having a lot of trouble figuring the new stuff out. I'm trying to follow all the instructions but I'm getting stuck constantly...

I had everything up and running with the previous ML-Agents and I have the Python 3.6.3 version installed. But when I do this:

To summarize, go to your command line, enter the ml-agents directory and type:
python3 python/learn.py <env_file_path> --run-id=<run-identifier> --train 

It says that python3 is not recognised as a command. Any clue whats going on? Probably I'm missing some stuff that is needed after the changes and not before, but after looking for hours I can't figure out what it is. 
I think that making a installation video would go a long way for people that are struggling like myself.

**Comment by vincentpierre** [comment]
@GeriBP If you are having problems please raise an issue.

**Pull request closed without merging**
