### PR TITLE
set multiple obstacles from area

### PR DESCRIPTION
**Pull request by brccabral**
added a parameter to GridArea to control how many obstacles will be created in the scene

### CODE REVIEW

**Comment by awjuliani** [comment]
Hi @brccabral 

Thanks for making this PR. It looks like you also change the default number of obstacles to 2 in the inspector here. Could you change that back to 1? Otherwise, I think our users will appreciate this additional flexibility.

**Comment by brccabral** [comment]
Done @awjuliani .

**Review by awjuliani — APPROVED** [review]
Looks good to me.

**Comment by awjuliani** [comment]
Thank you for the contribution, @brccabral !

**Pull request merged**
