### PR TITLE
Black formatting

### PR DESCRIPTION
**Pull request by eshvk**

### CODE REVIEW

**Comment by harperj** [comment]
Looks good, my only worry is that we don't have any explanation that external contributors need to run `black` for their PRs and how to do that.

Could be part of https://github.com/Unity-Technologies/ml-agents/blob/master/CONTRIBUTING.md

**Comment by eshvk** [comment]
@harperj fixed PTAL

**Comment by eshvk** [comment]
@harperj Can you explain this a little bit more? I added a line in `CONTRIBUTING.md` asking people to reformat code using `black` before submitting the PR. I am not sure what else is needed there?

**Comment by harperj** [comment]
Sorry @eshvk -- I must have missed that among all of the changes. PR looks good to me.

**Pull request merged**
