### PR TITLE
[Added Ascii art on learn.py]

### PR DESCRIPTION
**Pull request by vincentpierre**
Note : This is by far the best feature of 0.4

### CODE REVIEW

**Comment by vincentpierre** [comment]
Chose your favorite here http://patorjk.com/software/taag/#p=testall&f=Alpha&t=UNITY%0AML%20AGENTS

**Comment by awjuliani** [comment]
I vote for:

```
  _    _ _   _ _____ _________     __                       
 | |  | | \ | |_   _|__   __\ \   / /                       
 | |  | |  \| | | |    | |   \ \_/ /                        
 | |  | | . ` | | |    | |    \   /                         
 | |__| | |\  |_| |_   | |     | |                          
  \____/|_| \_|_____|  |_| ____|_|_____ _   _ _______ _____ 
 |  \/  | |          /\   / ____|  ____| \ | |__   __/ ____|
 | \  / | |         /  \ | |  __| |__  |  \| |  | | | (___  
 | |\/| | |        / /\ \| | |_ |  __| | . ` |  | |  \___ \ 
 | |  | | |____   / ____ \ |__| | |____| |\  |  | |  ____) |
 |_|  |_|______| /_/    \_\_____|______|_| \_|  |_| |_____/ 
```

**Comment by xiaomaogy** [comment]
I vote for:

```

 _____  _____ ____  _____ _____ _________ ____  ____                                      
|_   _||_   _|_   \|_   _|_   _|  _   _  |_  _||_  _|                                     
  | |    | |   |   \ | |   | | |_/ | | \_| \ \  / /                                       
  | '    ' |   | |\ \| |   | |     | |      \ \/ /                                        
   \ \__/ /   _| |_\   |_ _| |_   _| |_     _|  |_                                        
    `.__.'   |_____|\____|_____| |_____|   |______|                                       
 ____    ____ _____            _        ______  ________ ____  _____ _________   ______   
|_   \  /   _|_   _|          / \     .' ___  ||_   __  |_   \|_   _|  _   _  |.' ____ \  
  |   \/   |   | |    ______ / _ \   / .'   \_|  | |_ \_| |   \ | | |_/ | | \_|| (___ \_| 
  | |\  /| |   | |   |______/ ___ \  | |   ____  |  _| _  | |\ \| |     | |     _.____`.  
 _| |_\/_| |_ _| |__/ |   _/ /   \ \_\ `.___]  |_| |__/ |_| |_\   |_   _| |_   | \____) | 
|_____||_____|________|  |____| |____|`._____.'|________|_____|\____| |_____|   \______.' 
                                                                                          
```

**Comment by vincentpierre** [comment]
```
██╗   ██╗███╗   ██╗██╗████████╗██╗   ██╗                                   
██║   ██║████╗  ██║██║╚══██╔══╝╚██╗ ██╔╝                                   
██║   ██║██╔██╗ ██║██║   ██║    ╚████╔╝                                    
██║   ██║██║╚██╗██║██║   ██║     ╚██╔╝                                     
╚██████╔╝██║ ╚████║██║   ██║      ██║                                      
 ╚═════╝ ╚═╝  ╚═══╝╚═╝   ╚═╝      ╚═╝                                      
                                                                           
███╗   ███╗██╗          █████╗  ██████╗ ███████╗███╗   ██╗████████╗███████╗
████╗ ████║██║         ██╔══██╗██╔════╝ ██╔════╝████╗  ██║╚══██╔══╝██╔════╝
██╔████╔██║██║         ███████║██║  ███╗█████╗  ██╔██╗ ██║   ██║   ███████╗
██║╚██╔╝██║██║         ██╔══██║██║   ██║██╔══╝  ██║╚██╗██║   ██║   ╚════██║
██║ ╚═╝ ██║███████╗    ██║  ██║╚██████╔╝███████╗██║ ╚████║   ██║   ███████║
╚═╝     ╚═╝╚══════╝    ╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═╝  ╚═══╝   ╚═╝   ╚══════╝
```

**Comment by xiaomaogy** [comment]
@vincentpierre How does this look in a black background terminal?

**Comment by vincentpierre** [comment]
screen shot 2018-05-11 at 11 36 48 am
screen shot 2018-05-11 at 11 37 48 am
The color is random

**Comment by xiaomaogy** [comment]
I like the randomness in this.

**Comment by vincentpierre** [comment]
New ascii art ? 
```
                    ▄▄▄▓▓▓▓
               ╓▓▓▓▓▓▓█▓▓▓▓▓
          ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
        ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄
      ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌
    ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
    ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
      ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
        '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
           ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
               `▀█▓▓▓▓▓▓▓▓▓▌
                    ¬`▀▀▀█▓
 ```

**Pull request merged**
