### PR TITLE
When checking for the compatibility of the expert brain with the poli…

### PR DESCRIPTION
**Pull request by vincentpierre**
…cy brain, we will remove the action descriptions from the dictionary of things we need to compare. This is to prevent the case where a user has different descriptions for his actions but still wants to train a brain using expert demonstrations.

### CODE REVIEW

**Comment by chriselion** [comment]
Can you also update the error message to be more informative about which fields differ? That might have made https://github.com/Unity-Technologies/ml-agents/issues/2434#issuecomment-529146845 easier to debug for the user.

**Comment by vincentpierre** [comment]
@chriselion The whole reason we use dictionaries to compare the brain parameters is because we do not want to look at their fields individually.

**Comment by chriselion** [comment]
You could iterate over the dictionaries to get a list of the fields the differ, e.g.
```
different_keys = {k, v: policy_brain.items() if v != expert_brain[k]} - {"brain_name", "vector_action_descriptions"}
if different_keys:
  raise UnityTrainerException(...)
```
but not a big deal.

**Comment by ervteng** [comment]
Would actually support @chriselion's change since it doesn't require mutating or deepcopying anything.

**Comment by chriselion** [comment]
Can we ship this as it is? Seems like it still fixes a legit bug.

**Comment by vincentpierre** [comment]
Yes, we could. @ervteng what do you think ?

**Comment by ervteng** [comment]
Yeah let's do it. Approved.

**Pull request merged**
