### PR TITLE
Add note on curriculum learning documentation 

### PR DESCRIPTION
**Pull request by awjuliani**
### Proposed change(s)

* The example provided in the curriculum learning documentation was based on an old version of Wall Jump. As such, it is no longer replicable. Added a note to let users know that this is the case. 

This was brought to our attention here: https://github.com/Unity-Technologies/ml-agents/issues/3721

### Types of change(s)

- [ ] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Breaking change
- [X] Documentation update
- [ ] Other (please describe)

### Checklist
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Updated the [changelog](https://github.com/Unity-Technologies/ml-agents/blob/master/com.unity.ml-agents/CHANGELOG.md) (if applicable)
- [X] Updated the [documentation](https://github.com/Unity-Technologies/ml-agents/tree/master/docs) (if applicable)
- [ ] Updated the [migration guide](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Migrating.md) (if applicable)

### CODE REVIEW

**Comment by ervteng** [comment]
Hmm, running the current wall-jump will still result in a similar curve right? I'd be more in favor of just grabbing the last CI run of walljump-ppo-curri and saving the plot :P But otherwise the text looks good

**Comment by awjuliani** [comment]
@ervteng 

The issue is that a number of intermediate improvements to our trainers and to the physics/movement of the agent in WallJump resulted in no curriculum being needed to learn. In fact, it actually learns faster/better without one.

**Comment by andrewcoh** [comment]
I'm using curriculum for both Soccer and CubeWars. Let me know if you want me to update the curriculum doc using Soccer/CubeWars @awjuliani

**Comment by awjuliani** [comment]
@andrewcoh 

I think that would definitely be helpful. Do you think the curricula you use are demonstrative enough that we can just fully replace the Wall Jump example in the docs with it?

**Comment by vincentpierre** [comment]
Maybe we should create an environment that only demonstrates curriculum (it might be confusing if the same environment is used to demonstrate multi-agent and curriculum. Maybe we can create a simple environment that cannot be solved (or barely be solved) without curriculum.

**Comment by awjuliani** [comment]
I am up for a brainstorm session on this, though "a simple environment that cannot be solved (or barely be solved) without curriculum" may be mutually exclusive by definition.

**Comment by ervteng** [comment]
I think with Soccer we're using curriculum to give a small bonus reward for touching the ball, then remove this bonus later once the Agent gets used to that and can kick the ball in the goal. 
We could do something very similar with Pyramids (or a similarly sparse env), where we have a small incremental reward for a while (e.g. towards the target) but remove it later. It's not as illustrative as changing the wall height in WallJump, for sure.

**Comment by awjuliani** [comment]
Good point @ervteng 

I removed the graph and the accompanying text associated with it.

**Pull request merged**
