### PR TITLE
Localizing kr

### PR DESCRIPTION
**Pull request by JangHyeonJun**
I am a person who is interested in game AI. I'd like to try to make the document Korean.

### CODE REVIEW

**Comment by unityjeffrey** [comment]
hi @JangHyeonJun - thank you for the contribution.  can you change the target to "develop" instead of master"?  Also, I am working with our local korea team to find someone who can review.

**Comment by unityjeffrey** [comment]
hi @JangHyeonJun - thank you for your effort here.  we are in need of translation to korean for some of the documents.  obviously, it is way too much to try to do it all.  the main documents that would help are:

https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Basic-Guide.md
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Getting-Started-with-Balance-Ball.md

Jeff

**Comment by JangHyeonJun** [comment]
OK, I'm gonna change target and i will try to translate other 3 docs

**Comment by unityjeffrey** [comment]
thanks @JangHyeonJun - please use the Develop branch to work off of and submit PR.  Thanks, let us know if you need anything from us.

**Pull request closed without merging**
