### PR TITLE
Fix trainer_config.yaml

### PR DESCRIPTION
**Pull request by dongruoping**
remove wrong vis_encode_type config

### CODE REVIEW

**Comment by chriselion** [comment]
Whoops, we fixed this on the release branch but didn't merge it to develop:
https://github.com/Unity-Technologies/ml-agents/pull/2330/files

You might want to make that change instead, otherwise there are going to be merge conflicts later.

**Comment by dongruoping** [comment]
> Whoops, we fixed this on the release branch but didn't merge it to develop:
> https://github.com/Unity-Technologies/ml-agents/pull/2330/files
> 
> You might want to make that change instead, otherwise there are going to be merge conflicts later.

Fixed

**Comment by chriselion** [comment]
https://github.com/Unity-Technologies/ml-agents/pull/2346 will also fix this

**Comment by ervteng** [comment]
Don't merge this! We've merged the release fix back into develop to fix daily testing.

**Comment by dongruoping** [comment]
> Don't merge this! We've merged the release fix back into develop to fix daily testing.

Sure then I'll close this one.

**Pull request closed without merging**
