### PR TITLE
[bug-fix] Move POCA critic to default device

### PR DESCRIPTION
**Pull request by ervteng**
### Proposed change(s)

Move POCA critic to default device. Was failing Yamato GPU test without this. Needs to be cherry-picked into R15.

### Types of change(s)

- [x] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (please describe)

### Checklist
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Updated the [changelog](https://github.com/Unity-Technologies/ml-agents/blob/main/com.unity.ml-agents/CHANGELOG.md) (if applicable)
- [ ] Updated the [documentation](https://github.com/Unity-Technologies/ml-agents/tree/main/docs) (if applicable)
- [ ] Updated the [migration guide](https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Migrating.md) (if applicable)

### CODE REVIEW

**Review by vincentpierre — APPROVED** [review]
Do you manage to train on GPU after this fix ?

**Comment by ervteng** [comment]
> Do you manage to train on GPU after this fix ?

It's still failing: (Yamato job here: https://yamato.cds.internal.unity3d.com/jobs/497-ml-agents/tree/develop-poca-gpu/.yamato%252Fpytest-gpu.yml%2523pytest_gpu/5821068/job) need to debug

**Comment by dongruoping** [comment]
One thing I noticed in networks.py:line 271
`attn_mask = only_first_obs_flat.isnan().type(torch.FloatTensor)`
this will move tensors on cpu. 

Since we're using default tensor type we should avoid calling `torch.FloatTensor` and use `.float()` instead.
I've fixed several once before so I figured I should explicitly call this out.

**Comment by dongruoping** [comment]
Do you think we should enable gpu tests in all python PRs? I think we've seen couple times this fails in nightly CI and would be nice to catch them earlier.

**Comment by ervteng** [comment]
@dongruoping yep just caught that, the fix works 👍

**Comment by ervteng** [comment]
> Do you think we should enable gpu tests in all python PRs? I think we've seen couple times this fails in nightly CI and would be nice to catch them earlier.

I agree. Spoke with @surfnerd about this; I've added it to the Release Checklist. I guess we have to weight the cost of spinning up a GPU machine vs. catching these earlier. Not sure what the tradeoff is.

**Comment by dongruoping** [comment]
> @dongruoping yep just caught that, the fix works 👍

Can you also fix the `torch.BoolTensor` in the same file?

**Review by dongruoping — APPROVED** [review]

**Pull request merged**
