### PR TITLE
Made the _check_environment_trains test a little more easy to pass so…

### PR DESCRIPTION
**Pull request by vincentpierre**
… the test will not randomly fail

### CODE REVIEW

**Comment by chriselion** [comment]
Hopefully https://github.com/Unity-Technologies/ml-agents/pull/2524 and https://github.com/Unity-Technologies/ml-agents/pull/2521 mean that we'll have deterministic runs in the tests now. Can you hold off merging this and see if the others help?

**Comment by ervteng** [comment]
Hey @chriselion @vincentpierre the tests are still stochastic. e.g. for the last test (Marwan's commit 72088537) it was failing, and I re-ran it, and it passed. Seems like the culprit is usually PPO discrete. 

Not sure what would be causing it as we've set the tensorflow and numpy seeds.

**Comment by ervteng** [comment]
Reopening this PR

**Comment by chriselion** [comment]
🚢 🇮🇹

**Pull request merged**
