### PR TITLE
Update buffer.py

### PR DESCRIPTION
**Pull request by EfveZombie**
A simple fix of "Unable to shuffle if the fields are not of same length".

### CODE REVIEW

**Comment by unityjeffrey** [comment]
hi @EfveZombie - can you change target branch to Develop instead of master?  We do not allow PRs to Master this way.  Thanks!

**Comment by ervteng** [comment]
Hey @EfveZombie, thanks for adding this! Does using `dtype=np.float32` also fix your issue? IMO that would be a bit cleaner than `float`

**Comment by EfveZombie** [comment]
> Hey @EfveZombie, thanks for adding this! Does using `dtype=np.float32` also fix your issue? IMO that would be a bit cleaner than `float`

I think that would work too. 

In the old version, some part in buffer.py would return a ndarray with dtype=Object. The format was like `array([0.0, array([1.]), array([2.]), 3.0], dtype=object)`. So I tried to set the dtype manually and it work fine so far, but I still dont know what caused this problem.

**Comment by chriselion** [comment]
Issue link for reference: https://github.com/Unity-Technologies/ml-agents/issues/1798

**Comment by chriselion** [comment]
We think the root cause for this was fixed in https://github.com/Unity-Technologies/ml-agents/pull/2276. Going to close this, but if you have more problems, please reopen.

**Pull request closed without merging**
