### PR TITLE
Release 5 - Update versions and release strings

### PR DESCRIPTION
**Pull request by awjuliani**
### Proposed change(s)

Updates versions to Release 5.

### Types of change(s)

- [ ] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (please describe)

### Checklist
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Updated the [changelog](https://github.com/Unity-Technologies/ml-agents/blob/master/com.unity.ml-agents/CHANGELOG.md) (if applicable)
- [ ] Updated the [documentation](https://github.com/Unity-Technologies/ml-agents/tree/master/docs) (if applicable)
- [ ] Updated the [migration guide](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Migrating.md) (if applicable)

### CODE REVIEW

**Comment by chriselion** [comment]
You're going to need to cherry-pick https://github.com/Unity-Technologies/ml-agents/pull/4278 and https://github.com/Unity-Technologies/ml-agents/pull/4282 to get yamato tests to pass.

**Comment by awjuliani** [comment]
@chriselion Thanks for the heads-up. I get a merge conflict that I am not exactly sure how to resolve correctly, since I don't have experience with the yamato config files. Would you mind cherry-picking these for me?

**Comment by chriselion** [comment]
Sure, doing that in https://github.com/Unity-Technologies/ml-agents/pull/4290 to keep them separate. I think you're OK to merge this in the meantime

**Comment by awjuliani** [comment]
Thanks @chriselion I appreciate it!

**Pull request merged**
