### PR TITLE
Update Basic-Guide.md

### PR DESCRIPTION
**Pull request by laurentopia**
added missing instruction at the end

### CODE REVIEW

**Comment by unityjeffrey** [comment]
@laurentopia - can you rebase to develop instead?  Thanks!

**Comment by laurentopia** [comment]
@unityjeffrey I don't know what that means

**Comment by unityjeffrey** [comment]
sorry - i wrote that too fast.  meant to ask if you can change your branch to develop instead.

**Comment by laurentopia** [comment]
I'm not familiar with gh, I looked all over the settings for that fork and couldn't find such switch.

**Pull request merged**
